title: Syd Tremblay Portfolio
name: Syd Tremblay
email: w0840253@myscc.ca
baseulr: "/Syd-Tremblay-Portfolio/"

instagram: 
tiktok: 
vgen: 

collections:
designs:
output: true
permalink: /collection/:path/
